# Making changes? https://github.com/nektos/act may help you test locally

name: Publish

on:
  push:
      branches: [master, "mc/*"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v2
      - name: Setup JDK 14
        uses: actions/setup-java@v1
        with:
          java-version: 14
      - name: Cache Gradle packages
        uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-${{matrix.java}}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-${{matrix.java}}-gradle
      - name: Set up publishing
        uses: DamianReeves/write-file-action@v1.0
        with:
          path: ${{ env.HOME }}/.gradle/gradle.properties
          contents: ${{ secrets.PEX_REPO }}
          write-mode: overwrite
      - name: Make gradle wrapper executable
        run: chmod +x ./gradlew
      - name: Publish with Gradle
        run: ./gradlew publish
